name: Tests

on:
  push:
    branches:
      - main
      - dev

  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    container:
      image: rootproject/root:latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install package
        run: |
          python3 -m pip install --upgrade pip
          python3 -m pip install -e .
          python3 -m pip install pytest tabulate

      - name: Run tests
        run: |
          chmod +x run-test.sh
          ./run-test.sh
